#
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "10.0.3.22"
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.hostname = "srv-django"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.options = ["--verbose"]
    puppet.module_path = "puppet/modules"
end

end
